# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3b2ace00211d883ce1cb297b217ebc35c9e91b317f73f9b8746c99d18d3879a51887280bb77ea69d8845b21d2b4a2abc551a7a819b434e1f84f04da083c6253

test:
  secret_key_base: 6b0b9078abc7e9115a244ad981a161175d9c86a14c341685f572d729e9995d153ec37f67caa56b9a47f22329a88c8a7b3dd0462dfbfc3a1690e212f4f04f841b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
